project:
  type: website
  output-dir: docs

website:
  title: "Web Scraping With R. Course Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Presentation"
        contents: 
          - CourseIntro.qmd
        text: "Introduction to the course"
      - section: "Introducing R"
        contents:
          - RSessions.qmd
      - section: "Web Scraping"
        contents:
          - ScrapingSessions.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



