project:
  type: website
  output-dir: docs

website:
  title: "Web Scraping With R. Course Website"
  sidebar:
    background: primary
    style: docked
    search: true
    contents:
      - href: CourseIntro.qmd
        text: Home
      - href: RSessions.qmd
        text: Introduction to R
      - href: ScrapingSessions.qmd
        text: Web Scraping

format:
  html:
    theme: cosmo
#    css: styles.css
    toc: true



